# Generated by Django 2.2 on 2019-11-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background_task', '0003_auto_20191106_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_group',
            field=models.CharField(db_index=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_uid',
            field=models.CharField(db_index=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='completedtask',
            name='task_group',
            field=models.CharField(db_index=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='completedtask',
            name='task_uid',
            field=models.CharField(db_index=True, default=None, max_length=50, null=True),
        ),
    ]
